RL_algorithms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('environments/', include('environments.urls')),
    path('admin/', admin.site.urls),
]

environments/urls.py
from django.urls import path

from . import views

app_name = 'environments'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('search/', views.PostSearchView.as_view(), name='search'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/<pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('category-posts/<int:category_id>/', views.CategoryPostsListView.as_view(), name='category-posts'),
    path('category-post-detail/<int:category_id>/<pk>/', views.CategoryPostDetailView.as_view(), name='category-post-detail'),
    path('<pk>/', views.PostDetailView.as_view(), name='detail'),
    path('<int:post_id>/comment', views.create_comment, name='comment'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('theory/', views.theory, name='theory'),
    path('e_greedy/', views.e_greedy, name='e-greedy'),
    path('greedy/', views.greedy, name='greedy'),
    path('ucb/', views.ucb, name='ucb'),
]

environments/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=30)
    environment_name = models.CharField(max_length=25) # nome do ambiente escolhido pelo usuário para o post
    actions_number = models.IntegerField(default=0) # número de ações disponíveis no ambiente
    content = models.TextField(default="")
    creation_date = models.DateTimeField(default=timezone.now)
    gif_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.title} (Ambiente: {self.environment_name})'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username} em {self.post.environment_name}'
    
class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}: {self.description}'

staticpages/models.py
from django.db import models

# Create your models here.

environments/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'environment_name',
            'actions_number',
            'content',
            'gif_url',
        ]
        labels = {
            'title': 'Título',
            'environment_name': 'Ambiente',
            'actions_number': 'Número de ações',
            'content': 'Descrição do ambiente',
            'gif_url': 'URL do gif do ambiente',
        }
    
    def clean_gif_url(self):
        gif_url = self.cleaned_data.get('gif_url')

        if gif_url and not gif_url.startswith('https://gymnasium'):
            raise forms.ValidationError('O gif deve ser de um ambiente do gymnasium.')

        return gif_url

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

environments/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse, reverse_lazy
from django.views import generic
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm

class PostListView(generic.ListView):
    model = Post
    template_name = 'environments/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Ambientes'
        context['envpage_title'] = 'Encontre o ambiente ideal'
        context['category'] = False
        return context

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'environments/detail.html'

class PostSearchView(generic.ListView):
    model = Post
    template_name = 'environments/search.html'
    context_object_name = 'posts_list'

    def get_queryset(self):
        query = self.request.GET.get('query', '').lower()
        return Post.objects.filter(environment_name__icontains=query)

class PostCreateView(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'environments/create.html'

    def get_success_url(self):
        return reverse('environments:detail', kwargs={'pk': self.object.pk})

class PostUpdateView(generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'environments/update.html'

    def get_success_url(self):
        return reverse('environments:detail', kwargs={'pk': self.object.pk})

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'environments/delete.html'

    def get_success_url(self):
        return reverse('environments:index')

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('environments:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'environments/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'environments/categories.html'

class CategoryPostsListView(generic.ListView):
    template_name = 'environments/index.html'
    context_object_name = 'post_list'

    def get_category(self):
        return Category.objects.get(pk=self.kwargs['category_id'])

    def get_queryset(self):
        return self.get_category().posts.all()
    
    def get_context_data(self, **kwargs):
        category = self.get_category()
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Categoria'
        context['envpage_title'] = f'Categoria {category.name}'
        context['category'] = True
        context['category_id'] = category.id
        return context

class CategoryPostDetailView(generic.DetailView):
    model = Post
    template_name = 'environments/detail.html'

    def get_object(self):
        category_id = self.kwargs.get('category_id')
        pk = self.kwargs.get('pk')
        category = Category.objects.get(pk=category_id)
        posts = category.posts.all()
        post = get_object_or_404(posts, pk=pk) 
        return post

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def theory(request):
    context = {}
    return render(request, 'staticpages/theory.html', context)

def e_greedy(request):
    context = {}
    return render(request, 'staticpages/e_greedy.html', context)

def greedy(request):
    context = {}
    return render(request, 'staticpages/greedy.html', context)

def ucb(request):
    context = {}
    return render(request, 'staticpages/ucb.html', context)

environments/templates/environments/categories.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Categorias
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_environments.css' %}">
{% endblock pagestyle %}

{% block content %}
<h2>Categorias de ambientes</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <div class="link-columns">
                <div class="link-column">
                    <a href="{% url 'environments:category-posts' category.id %}">
                        <h3>
                            <span class="material-icons">category </span>
                            {{ category.name }}
                        </h3>
                    </a>
                </div>
            </div>
        </header>
        <p>{{ category.description }}</p>
        <h4>
            <span class="material-icons">rocket_launch </span>
            Ambientes
        </h4>
        {% for post in category.posts.all %}
        <p id="env-name">
            <i>{{ post.environment_name }}</i>
        </p>
        {% endfor %}
    </article>
    {% endfor %}
</section>

{% endblock content %}

environments/templates/environments/comment.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Comentar
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_environments.css' %}">
{% endblock pagestyle %}

{% block content %}

<h2>Comentar em {{ post.title }} (<i>{{ post.environment_name }}</i>)</h2>

<form action="{% url 'environments:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Comentar</button>
</form>

<p><a href="{% url 'environments:detail' post.id %}">Voltar para a página do post</a></p>
{% endblock content %}

environments/templates/environments/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Criar Post
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_environments.css' %}">
{% endblock pagestyle %}

{% block content %}
<h2>Adicionar novo post</h2>
<form method="POST" action="{% url 'environments:create' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Criar</button>
</form>

{% endblock content %}

environments/templates/environments/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Apagar Post
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_environments.css' %}">
{% endblock pagestyle %}

{% block content %}
<form action="{% url 'environments:delete' post.id %}" method="post">
  {% csrf_token %}
  <p>
    Você tem certeza que deseja apagar o post "{{ post.title }} do ambiente <i>{{ post.environment_name }}</i>"?
  </p>
  <button type="submit">Apagar</button>
</form>
{% endblock content %}

environments/templates/environments/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ post.environment_name }}
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_environments.css' %}">
{% endblock pagestyle %}

{% block content %}
<div class ="post">
  <section class="env-data">
    <div class="post-content">
      <div class="post-header">
          <span id="post-author">Descrição do ambiente</span>
          <span id="post-date">Criação: {{ post.creation_date|date:"j/m/y" }} às {{ post.creation_date|date:"H:i" }}</span>
      </div>
      <div class="post-body">
        <h3>{{ post.title }}</h3>
        <div>
          {{ post.content|safe }}
        </div>
        <img src="{{ post.gif_url }}" alt="GIF do ambiente {{ post.environment_name }}" class="env-image"/>
        <div class="post-attributes">
          <table>
              <tr id="env-row">
                  <td>Ambiente</td>
                  <td>{{ post.environment_name }}</td>
              </tr>
              <tr id="actions-row">
                  <td>Número de ações</td>
                  <td>{{ post.actions_number }}</td>
              </tr>
          </table>
          {% if post.category_set.all %}
          <p>Incluso nas categorias:</p>
          <div class="link-columns">
            {% for category in post.category_set.all %}
            <div class="link-column">
              <a href="{% url 'environments:category-posts' category.id %}">
                <span class="material-icons">category </span> 
                {{ category.name }} 
              </a>
            </div>
            {% endfor %}
          </div>
          {% endif %}
        </div>
      </div>
      <div class="link-columns">
        <div class="link-column">
          <a href="{% url 'environments:update' post.id %}">
            <span class="material-icons">edit </span>
            Editar
          </a>
        </div>
        <div class="link-column">
          <a href="{% url 'environments:delete' post.id %}">
            <span class="material-icons">delete </span>
            Apagar
          </a>
        </div>
      </div>
    </div>
  </section>
</div>

<hr>

<section>
    <header>
        <h3>
          <span class="material-icons">forum </span>
          Comentários
        </h3>
    </header>
    {% if post.comment_set.all %}
        {% for comment in post.comment_set.all|dictsortreversed:"date" %}
            <figure>
                <figcaption>
                  <span class="material-icons">account_circle </span>
                  {{ comment.author }}<br>
                  {{ comment.date|date:"j/m/y" }} às {{ comment.date|date:"H:i" }}
                </figcaption>
                <blockquote>
                    <span class="material-icons">chat </span>
                    {{ comment.text }}
                </blockquote>
            </figure>
            <br>
        {% endfor %}
    {% else %}
        <p>Não foi comentado nada sobre esse post. Adicione sua opinião sobre esse ambiente.</p>
    {% endif %}

    <a href="{% url 'environments:comment' post.pk %}"><button>Comente</button></a>
</section>
<br>
{% endblock content %}

environments/templates/environments/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ page_title }}
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_environments.css' %}">
{% endblock pagestyle %}

{% block content %}
<h2 id="envpage-title">{{ envpage_title }}</h2>
{% if not category %}
<section>
  <p> 
    Essa página reúne exemplos de ambientes discretos para treinar seus agentes. Clique sobre a imagem para acessar o post.
  </p>
  <div class="link-columns">
    <div class="link-column">
      <a href="{% url 'environments:search' %}">
        <span class="material-icons">search </span>
        Buscar Ambientes
      </a>
    </div>
    <div class="link-column">
      <a href="{% url 'environments:create' %}">
        <span class="material-icons">add </span>
        Adicionar Novo Ambiente
      </a>
    </div>
  </div>
</section>
{% endif %}
{% if post_list %}  <!-- checa se não está vazia -->
<section class="cards-list">
    {% for post in post_list %}
    <article class="card">
      <div class="card-content">
        <h3>{{ post.title }}</h3>
        {% if not category %}
        <a href="{% url 'environments:detail' post.id %}">
          <img src="{{ post.gif_url }}" alt="GIF do ambiente {{ post.environment_name }}" />
        </a>
        {% else %}
        <a href="{% url 'environments:category-post-detail' category_id post.id %}">
          <img src="{{ post.gif_url }}" alt="GIF do ambiente {{ post.environment_name }}" />
        </a>
        {% endif %}
      </div>
      <p id="env-name">
        <i>{{ post.environment_name }}</i>
      </p>
      <p>
        <span class="material-icons">calendar_month </span>
        Criado em: {{ post.creation_date|date:"j/m/y" }} às {{ post.creation_date|date:"H:i" }}
      </p>
    </article>
  {% endfor %}
</section>
{% else %}
<p>Não há nenhum ambiente registrado.</p>
{% endif %} {% endblock content %}

environments/templates/environments/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Busca
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_environments.css' %}">
{% endblock pagestyle %}

{% block content %}
<h2>Busca por um ambiente</h2>
<form action="{% url 'environments:search' %}">
    <p>
        <label for="id_query">Ambiente:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if posts_list %}
<section class="cards-list">
    {% for post in posts_list %}
    <article class="card">
        <div class="card-content">
          <h3>{{ post.title }}</h3>
          <a href="{% url 'environments:detail' post.id %}">
            <img src="{{ post.gif_url }}" alt="GIF do ambiente {{ post.environment_name }}" />
          </a>
        </div>
        <p id="env-name">
          <i>{{ post.environment_name }}</i>
        </p>
        <p>
          <span class="material-icons">calendar_month </span>
          Criado em: {{ post.creation_date|date:"j/m/y" }} às {{ post.creation_date|date:"H:i" }}
        </p>
      </article>
    {% endfor %}
</section>
{% else %}
<p>O ambiente {{ post.environment_name }} não foi registrado em nenhum de nossos posts.</p>
{% endif %}

{% endblock content %}

environments/templates/environments/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Editar Post
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_environments.css' %}">
{% endblock pagestyle %}

{% block content %}
<h2>Editar post {{ post.title }} do ambiente <i>{{ post.environment_name}}</i></h2>
<form method="POST" action="{% url 'environments:update' post.id%}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Atualizar</button>
</form>
{% endblock content %}

staticpages/templates/staticpages/e_greedy.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Algoritmos
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_infopages.css' %}">
{% endblock pagestyle %}

{% block content %}
<h2>ε-greedy</h2>
<p>
    O algoritmo <i>ε-greedy</i> busca balancear exploração e ações gananciosas. 
    Embora em curto prazo o <i>greedy</i> pode desempenhar melhor do que esse algoritmo, 
    quando consideramos uma <i>run</i> com um número muito grande de <i>steps</i> é o <i>ε-greedy</i> 
    que obtém valores maiores de recompensa, uma vez que podendo explorar em alguns momentos, o último 
    apresenta a possibilidade de conhecer os valores de todas as ações, determinando, assim, a ação ideal 
    e podendo se aproveitar dela.
</p>
<p>
    No entanto, se a cada passo o agente escolher aleatoriamente uma ação, ele terá uma chance de 
    1/<i>k</i> de escolher uma ação <i>a</i> e assumindo que ela possui valor maior do que todas as outras, 
    o agente iria escolher a ação ideal em 1/<i>k</i> dos casos. Nesse sentido, o algoritmo não deve 
    explorar sempre, buscando encontrar um ponto de equilíbrio ideal entre o número de vezes em que 
    decide explorar e o número em que decide escolher a ação com valor esperado máximo. Assim, 
    define-se a escolha desse algoritmo como:
</p>
<img class="math_equation" src="{% static 'images/egreedy.jpg' %}" alt="Seleção de ação no algoritmo">
<p>
    Da formulação acima, segue que para um número grande de steps o algoritmo irá selecionar a 
    ação ideal com uma probabilidade maior que (1 - ε). Precisamente irá selecioná-la com uma 
    probabilidade igual a (1 - ε + ε * 1/<i>k</i>). Tendo essa definição em mente, o código fica como se segue:
</p>
<div class="code-slide">
    <pre>
        <code>
    class EpsilonGreedy():
        def __init__(self, k_arms, epsilon=0.1):
            self.epsilon = epsilon
            self.k_arms = k_arms
            self.n_arms = np.zeros(k_arms)
            self.Q_values = np.zeros(k_arms)
            self.last_action = np.random.randint(0, k_arms)

        def agent_step(self, reward):

            self.n_arms[self.last_action] += 1
            current_Q = self.Q_values[self.last_action] + (reward - self.Q_values[self. last_action])/self.n_arms[self.last_action]
            self.Q_values[self.last_action] = current_Q

            u = np.random.random() # número aleatório real entre 0 e 1

            if u < self.epsilon:
                current_action = np.random.randint(0, self.k_arms)
            else:
                current_action = argmax(self.Q_values)

            self.last_action = current_action

            return self.last_action
        </code>
    </pre>
</div>
<p>
    Comparando com o código para <i>greedy</i>, a parte diferente é a seleção da próxima ação, 
    em que o número gerado aleatoriamente entre 0 e 1 deve ser menor que o valor atribuído a ε 
    na criação do agente (<i>default</i> igual a 0.1) para que ocorra exploração. Com 3000 <i>steps</i> 
    agora na simulação e atribuindo diversos valores para ε (inclusive zero que equivale ao <i>greedy</i>) 
    para fins de comparação, o resultado obtido para o agente treinado encontra-se na figura abaixo.
</p>
<img class="content__image" src="{% static 'images/egreedy_performance.jpg' %}" alt="Curva para ε-greedy">
<p>
    Os resultados obtidos indicam que o algoritmo com ε = 0 e com ε = 0.5 (muitas ações 
    aleatoriamente escolhidas) são os que desempenham pior no sentido de que a curva de 
    recompensa média para de crescer com um número relativamente baixo de steps. É possível 
    observar que o <i>greedy</i> cresce mais rapidamente no início que os demais, mas para de crescer 
    antes também.
</p>
<p>
    Já para ε = 0.01 e ε = 0.05, como há o fenômeno de exploração, os agentes não ficam 
    travados em um ação específica logo de cara, de modo que a recompensa continua a subir 
    ao longo dos steps. A tendência é que aumentando o número de steps, esses algoritmos 
    sejam capazes de identificar a ação com maior valor esperado e consigam desempenhar melhor.
</p>

{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Página inicial
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_infopages.css' %}">
{% endblock pagestyle %}

{% block content %}
<p>
    Esse site é voltado para o estudo dos dois elementos centrais em Aprendizado por Reforço 
    (<i>Reinforcement Learning</i>): agente e ambiente.
</p>
<p>
    A proposta é apresentar a teoria de um problema inicial da teoria de RL, algoritmos que 
    possibilitam o entendimento de como o agente se comporta diante do meio e possibilitar
    discussões acerca dos diferentes tipos de ambientes conhecidos pela comunidade.
</p>
<figure>
    <figcaption id="image__title">
        Esquema para a relação fundamental de RL entre o agente e o meio
    </figcaption>
    <img class="content__image" src="{% static 'images/RL_diagram.png' %}" alt="Diagrama aprendizado por reforço">
    <figcaption id="image__legend">
        A imagem acima foi retirada do livro Reinforcement Learning: An Introduction escrito por 
        Richard S. Sutton e Andrew G. Barto
    </figcaption>
</figure>
{% endblock content %}

staticpages/templates/staticpages/ucb.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Algoritmos
{% endblock title %}

{% block pagestyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_infopages.css' %}">
{% endblock pagestyle %}

{% block content %}
<h2>UCB</h2>
<p>
    O nome UCB vem de <i>Upper-Confidence-Bound</i> ou Intervalo Superior de Confiança. 
    Esse algoritmo também busca inserir a exploração na tomada de ações, mas ao contrário 
    do ε-greedy, as ações não são totalmente aleatórias na exploração. Utiliza-se o 
    intervalo de confiança para selecionar ações próximas ao valor máximo, cujo valor 
    de incerteza leva a borda superior para o valor máximo, de modo que esta será retornada 
    pela função <i>argmax</i>.
</p>
<img class="math_equation" src="{% static 'images/ucb.jpg' %}" alt="Equação que define o limite superior">
<p>
    No argumento passado para a função, o primeiro termo corresponde ao comportamento 
    <i>exploit</i> enquanto que o segundo ao <i>explore</i>. Em termos da seleção gananciosa de ação, 
    quanto maior for o valor estimado para a ação, maior será o resultado da soma. 
    Já em relação à exploração, à medida que o tempo <i>t</i> cresce sem que a ação <i>a</i> 
    seja tomada (o denominador <i>N</i> permanece constante), o segundo termo que está 
    associado à incerteza aumenta fazendo com que todas as ações sejam eventualmente 
    escolhidas quando esse número se torna maior. A constante <i>c</i> controla a taxa de 
    exploração do algoritmo, cuja implementação é apresentada: 
</p>
<div class="code-slide">
    <pre>
        <code>
    class UCB():
        def __init__(self, k_arms, c_param=0.1):
            self.c_param = c_param
            self.k_arms = k_arms
            self.n_arms = np.zeros(k_arms)
            self.Q_values = np.zeros(k_arms)
            self.UCB_values = np.zeros(k_arms)
            self.last_action = np.random.randint(0, k_arms)

        def agent_step(self, reward):

            self.n_arms[self.last_action] += 1
            current_Q = self.Q_values[self.last_action] + (reward - self.Q_values[self.last_action])/self.n_arms[self.last_action]
            self.Q_values[self.last_action] = current_Q

            for a in range(self.k_arms):
            if self.c_param == 0:
                self.UCB_values[a] = self.Q_values[a]
            elif self.n_arms[a] == 0:
                self.UCB_values[a] = float("inf")
            else:
                self.UCB_values[a] = self.Q_values[a] + self.c_param * np.sqrt(np.log(np.sum(self.n_arms))/self.n_arms[a])

            current_action = argmax(self.UCB_values)
            self.last_action = current_action

            return self.last_action
        </code>
    </pre>
</div>
<p>
    Com o agente treinado, foram simuladas 200 rodadas com 1000 instantes discretos de 
    tempo em cada uma, atingindo um valor de recompensa média bastante alto e bem rápido 
    se comparar com os demais algoritmos.
</p>
<img class="content__image" src="{% static 'images/ucb_performance.jpg' %}" alt="Curva para UCB">
<p>
    Nos steps iniciais os valores esperados estão sendo atualizados para todas as ações 
    (exploração), uma vez que no limite em que o número de ocorrência de cada ação é zero, 
    o valor correspondente em UCB tende a infinito, de modo que pela função argmax, 
    será escolhida uma ação aleatoriamente. Posteriormente, a escolha de ação é com 
    base no limite de confiança. Para c = 0, tem se o caso do <i>greedy</i> novamente.
</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Aprendizado por Reforço
    </title>
    <link  rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block pagestyle %}
    {% endblock pagestyle %}
</head>

<body>
    <header id="staticpages-header">
        <h1>Aprendizado por Reforço</h1>
        <nav id="staticpages-nav">
            <ul>
                <li class="nav__item"><a href="{% url 'index' %}">
                    <span class="material-icons">home </span>
                    Home
                </a></li>
                <li class="nav__item"><a href="{% url 'theory' %}">
                    <span class="material-icons">book </span>
                    Teoria
                </a></li>
                <li id="algorithm-item">
                    <span class="material-icons">terminal </span>
                    Algoritmos
                    <div class="dropdown">
                        <a href="{% url 'greedy' %}">1. greedy</a>
                        <a href="{% url 'e-greedy' %}">2. ε-greedy</a>
                        <a href="{% url 'ucb' %}">3. UCB</a>
                    </div>
                </li>
                <li class="nav__item"><a href="{% url 'environments:index' %}">
                    <span class="material-icons">rocket </span>
                    Ambientes
                </a></li>
                <li class="nav__item"><a href="{% url 'environments:categories' %}">
                    <span class="material-icons">category </span>
                    Categorias
                </a></li>
            </ul>
        </nav>
    </header>
    <main id="staticpages-main">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="staticpages-footer">
        <p> Copyright 2023 Vítor Viana </p>
    </footer>
</body>

</html>